CREATE DATABASE  IF NOT EXISTS `public_housing`;
USE `public_housing`;
/*-----------------First Part------------------------*/
SELECT * FROM public_housing_inspections;
DROP TABLE IF EXISTS most_recent;
CREATE TABLE most_recent AS
SELECT PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME, 
INSPECTION_DATE AS MR_INSPECTION_DATE, 
COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST, 
LEAD(INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST,
COST_OF_INSPECTION_IN_DOLLARS - (LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC)) AS CHANGE_IN_COST,
((COST_OF_INSPECTION_IN_DOLLARS - (LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC)))/
	(LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC))) * 100 AS PERCENT_CHANGE_IN_COST,
ROW_NUMBER() OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC) AS RECENT_ID
FROM public_housing_inspections
ORDER BY  PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC; 
SELECT * FROM most_recent;
/*-----------------------------------------Second Part-----------------------------------*/

SELECT most_recent.PHA_NAME, most_recent.MR_INSPECTION_DATE, 
most_recent.MR_INSPECTION_COST, most_recent.SECOND_MR_INSPECTION_DATE, 
most_recent.SECOND_MR_INSPECTION_COST, most_recent.CHANGE_IN_COST, 
most_recent.PERCENT_CHANGE_IN_COST
FROM most_recent
WHERE most_recent.RECENT_ID=1 AND (CHANGE_IN_COST>0);